when@dev:
    snc_redis:
        # Define your clients here. The example below connects to database 0 of the default Redis server.
        # See https://github.com/snc/SncRedisBundle/blob/master/docs/README.md for instructions on
        # how to configure the bundle.
        clients:
            # @snc_redis.local
            local:
                type: predis
                alias: local
                dsn: "%env(REDIS_URL)%"
                logging: '%kernel.debug%'

            # @snc_redis.remote
            remote:
                type: predis
                dsn: "%env(REDIS_REMOTE_URL)%"
                logging: '%kernel.debug%'

when@test:
    snc_redis:
        clients:
            local:
                type: predis
                dsn: "%env(TEST_REDIS_URL)%"

            remote:
                type: predis
                dsn: "%env(TEST_REDIS_URL)%"

###
# NO snc_redis PROD BUNDLE !
###
