
networks: 
    sym:

volumes:
    mysql:

services: 
    ############
    # DATABASE #
    ############
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: mydb
            MYSQL_TCP_PORT: 3306 # Mandatory 3306 for Adminer
        volumes:
            - .docker/data/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - .docker/data/mysql/conf.d/my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
            - mysql:/var/lib/mysql
        networks: [sym]

    ##############
    # Key-values #
    ##############
    redis:
        image: redis:6.0  
        restart: always
        volumes: 
            - .docker/data/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
        # ports: [6379:6379]
        networks: [sym]

    #########
    # ADMIN #
    #########

    adminer:
        image: adminer:4-standalone
        restart: always
        ports: [8081:8080]
        networks: [sym]

    redisadmin:
        image: erikdubbelboer/phpredisadmin
        restart: always
        environment:
            - REDIS_1_HOST=redis
            - REDIS_1_NAME=AppRedis
        ports: [8082:80]
        networks: [sym]

    # phpmyadmin:
    #     image: phpmyadmin:5.0
    #     restart: always
    #     ports: 
    #         - 8081:80
    #     environment: 
    #         - PMA_ARBITRARY=1
    #     external_links:
    #         - mysql:mysql
    #     networks:
    #         - sym
