# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # @TODO use "app.redis.enabled" parameters
    use_redis: ~ # ~|local|remote

services:
    # _default configuration for services in !this! file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    _instanceof:
        # App LOGGER used in TextBundle #
        App\MainBundle\Contract\LoggerAwareInterface:
            calls:
                - ['setLogger', ['@app.logger']]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    # MainBundle Contract #
    App\MainBundle\Contract\:
        resource: ../src/MainBundle/Contract

    # MainBundle Admin #
    App\MainBundle\Controller\Admin\:
        resource: ../src/MainBundle/Controller/Admin

    # MainBundle - All components #
    App\MainBundle\:
        resource: ../src/MainBundle
        exclude:
            - ../src/MainBundle/MainBundle.php
            - ../src/MainBundle/Resources/

    # Front #
    App\FrontBundle\:
        resource: ../src/FrontBundle

    # Play #
    # App\PlayBundle\:
    #     resource: ../src/PlayBundle

    # Encrypt #
    # App\Encrypt\:
    #     resource: ../src/Encrypt/
    #     exclude:
    #         - ../src/Encrypt/Domain/Model/EncryptedData.php

    # Text #
    App\TextBundle\:
        resource: ../src/TextBundle

    # App\AppBundle\Domain\WorkflowInterface: '@App\AppBundle\Infrastructure\Manager\AppWorkflowManager'



    ################
    ### Specific ###
    ################

liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/doctrine-extensions/DoctrineExtensions/tree/main/doc
# stof_doctrine_extensions:
#     default_locale: en_US
